### PR TITLE
Clean up paths

### PR DESCRIPTION
**Pull request by AlexeyRaga**
Merge at will

### CODE REVIEW

**Comment by newhoggy** [comment]
```
$ rm -rf ~/moo
$ rm -rf ~/.cabal/archive
$ time hw-ci-assist sync-to-archive --threads 16
hw-ci-assist: /Users/jky/.cabal/archive/ghc-8.6.4/lib: getDirectoryContents:openDirStream: does not exist (No such file or directory)
hw-ci-assist sync-to-archive --threads 16  0.11s user 0.07s system 179% cpu 0.098 total
```

**Comment by newhoggy** [comment]
I think something broke because the old version works:

```
$ hw-ci-assist sync-to-archive --threads 16
Creating /Users/jky/.cabal/archive/ghc-8.6.4/bs-rphns-0.8.1-709cc779.tar.gz
Creating /Users/jky/.cabal/archive/ghc-8.6.4/blz-mrkp-0.8.2.2-517bc98d.tar.gz
Creating /Users/jky/.cabal/archive/ghc-8.6.4/cndt-xtr-1.3.1.1-f12ea1b5.tar.gz
...
Creating /Users/jky/.cabal/archive/ghc-8.6.4/xml-cndt-1.8.0.1-1491bcc0.tar.gz
Creating /Users/jky/.cabal/archive/ghc-8.6.4/xml-typs-0.3.6-d5df4487.tar.gz
Creating /Users/jky/.cabal/archive/ghc-8.6.4/zlb-0.6.2-18f6284f.tar.gz
```

**Comment by AlexeyRaga** [comment]
Yes, I fixed that. 
Tested the roundtrip, could compile this project after restoring.

**Comment by newhoggy** [comment]
Already merged with fixes.

**Comment by AlexeyRaga** [comment]
NOT ALL OF IT! :)

**Comment by AlexeyRaga** [comment]
i'll create a merge

**Pull request closed without merging**
